Use ruff for linting
koenhendriks/ha-button-plus pull request #58
Opened 2024-04-09 09:59 UTC by bolkedebruin

This adds a github workflow that uses ruff for linting.

2024-04-09 10:31 UTC, koenhendriks requested changes

2024-04-09 10:31 UTC, koenhendriks commented on .github/workflows/ruff.yml
Let's put this in the existing `validate.yml` in this directory.

2024-04-09 13:08 UTC, bolkedebruin commented on .github/workflows/ruff.yml
I suggest not doing that, as the validate is there for a separate use case (hass / hacs) and this is a separate test. Also github can run the tests in parallel now otherwise it cannot.

2024-04-10 06:51 UTC, koenhendriks commented on .github/workflows/ruff.yml
I've more experience in Gitlab Pipelines than Github Actions so I'll trust your judgement on this :)

2024-04-10 06:52 UTC, koenhendriks commented
@bolkedebruin If you fix the lint issues I'll approve the PR :D

2024-04-10 14:06 UTC, merged